# Generated by Django 3.2.7 on 2021-10-19 17:42

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follow_like_post'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('follower', django.db.models.expressions.F('followed')), _negated=True), name='users_cannot_follow_themselves'),
        ),
    ]
